### ISSUE TITLE
安装后，后台提示Call to undefined method support\\Request::more()这个问题

### ISSUE THREAD

**Issue by new123-ui** [saithink/saiadmin#1]
![image](https://github.com/saithink/saiadmin/assets/74286077/3d1ed31a-bb2b-4b44-9cd9-b8f281ca9ded)

**Comment by saithink** [comment]
这个问题的解决方法在官方文档已经说明：
https://saithink.top/guide/install.html#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE

**Comment by new123-ui** [comment]
![image](https://github.com/saithink/saiadmin/assets/74286077/9129cce4-d252-4058-b50c-dd45d0b15f32)
配置的新的模块，然后复制了所以的代码，以及执行了sql语句，但是在访问板块的时候，报错了，页面是有的，但是请求的接口地址也是错误，是为什么呢
![image](https://github.com/saithink/saiadmin/assets/74286077/39d8b41a-61dc-4796-81f3-45cb1446579e)
![image](https://github.com/saithink/saiadmin/assets/74286077/20e0c55b-43a7-4200-ba36-166cc0750444)

**Comment by new123-ui** [comment]
webman的后端请求路由地址：
![image](https://github.com/saithink/saiadmin/assets/74286077/f9becf64-e429-4ac0-8c7c-39bfc2629c1b)
前端的页面展示数据：
![image](https://github.com/saithink/saiadmin/assets/74286077/33625c7d-d5d3-49b1-bcdc-4b8c137164a7)

**Comment by new123-ui** [comment]
后端控制层代码
![image](https://github.com/saithink/saiadmin/assets/74286077/682887bf-a045-4a4c-8278-e872801157dd)

**Comment by saithink** [comment]
建议不要生成在框架核心代码里面，直接在app目录下建立应用或者在自己创建plugin进行开发
