### ISSUE TITLE
增强图片上传

### ISSUE THREAD

**Issue by sorshion** [saithink/saiadmin#19]
使用阿里云上传，图片不显示，数据库里面存的是相对路径，而本地上传，数据库又是存的绝对路径，这一块不太合理

**Comment by sorshion** [comment]
[20](https://github.com/saithink/saiadmin/pull/20)

**Comment by saithink** [comment]
是否有配置自定义域名，阿里云应该也需要配置，我这边没有阿里云账户，如果能给出具体情况和方案帮助项目完善，那会更好

**Comment by saithink** [comment]
感谢提出的pr解决方案
