### ISSUE TITLE
自动生成的代码如何修改时间字段？

### ISSUE THREAD

**Issue by yun3948** [saithink/saiadmin#3]
大佬你好，我这边接口模块计划使用 eloquent，然后习惯问题使用了 webman-admin 创建数据表，webman-console 命令生成 model 文件，
然后发现这个saiadmin 自动生成代码使用的是thinkorm,里面的时间字段是不一致的，我这边想新建一个 基类 model，覆盖里面的 时间字段和方法，不知道这种想法可不可行，然后其他地方有没有需要修改的？感谢

**Comment by saithink** [comment]
可以，也可以直接修改模型基类里面的字段
