### ISSUE TITLE
菜单点不动..

### ISSUE THREAD

**Issue by xee2211** [saithink/saiadmin#5]
**菜单混合模式下..系统设置没有子菜单的情况下,点不动**

<img width="1224" alt="image" src="https://github.com/saithink/saiadmin/assets/152939448/38361fca-413e-4d1a-91f0-4a121cd52fcd">

**菜单混合模式下..系统设置没有子菜单的情况下,点不动**

**Comment by saithink** [comment]
这个在main分支中已经修复了
