### ISSUE TITLE
2.0版本保存个人信息是会提示字段不存在的情况

### ISSUE THREAD

**Issue by haoqianlei** [saithink/saiadmin#8]
1.0版本没有出现此问题
php：8.1.10
workerman/webman-framework: v1.5.20
![image](https://github.com/saithink/saiadmin/assets/22309178/3836d4d9-9fa6-44f1-948f-7757539dc97a)

**Comment by saithink** [comment]
暂未测试出此问题，能否针对报错进行跟踪分析出问题的原因？
